affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 5
symbolic.funs_name.0:
- - 1/x^0.5
  - x^2
  - '0'
symbolic.funs_name.1:
- - 1/x^2
symbolic_enabled: true
width:
- - 3
  - 0
- - 1
  - 0
- - 1
  - 0
